### ISSUE TITLE
HU2 "Yo como usuaria quiero tomar nota para no depender de mi mala memoria y tener presente en todo momento los apuntes ó cosas importantes que antes escribía en papel"

### ISSUE THREAD

**Issue by NanciMondragon** [NanciMondragon/CDMX012-notes#3]
*** Criterios de Aceptación

- [x]  Debería poder tomar nota
- [x] Anotar un título a mi nota
- [x] Agregar el contenido de mi nota.
- [x] Botón de "Compartir"
- [x] Se visualiza en tablet

*** Criterios de Terminado

- [x] Debe ser responsive
- [x] Debe ser SPA
- [x] Se deben modularizar los archivos
